version: "3"
services:
  postgis:
    image: pgrouting/pgrouting:13-3.0-master
    ports:
      - "5432:5432"
    volumes: 
      - ./data/1_prepare_db.sql:/docker-entrypoint-initdb.d/1_prepare_db.sql
      - ./data/2_import_ways.sql:/docker-entrypoint-initdb.d/2_import_ways.sql
      - ./data/3_setup_tables.sql:/docker-entrypoint-initdb.d/3_setup_tables.sql
    environment:
      - POSTGRES_PASSWORD=postgres
volumes:
   data: